
class_names = [
    'net.datafaker.annotations.FakeResolver',
    'net.datafaker.internal.helper.SingletonLocale',
    'net.datafaker.internal.helper.WordUtils',
    'net.datafaker.providers.base.Artist',
    'net.datafaker.providers.base.Australia',
    'net.datafaker.providers.base.Chiquito',
    'net.datafaker.providers.base.CultureSeries',
    'net.datafaker.providers.base.DateAndTime',
    'net.datafaker.providers.base.Demographic',
    'net.datafaker.providers.base.Disease',
    'net.datafaker.providers.base.Drone',
    'net.datafaker.providers.base.DungeonsAndDragons',
    'net.datafaker.providers.base.FamousLastWords',
    'net.datafaker.providers.base.Hashing',
    'net.datafaker.providers.base.Horse',
    'net.datafaker.providers.base.Medical',
    'net.datafaker.providers.base.Military',
    'net.datafaker.providers.base.OlympicSport',
    'net.datafaker.providers.base.Photography',
    'net.datafaker.providers.base.ProgrammingLanguage',
    'net.datafaker.providers.base.RockBand',
    'net.datafaker.providers.base.Science',
    'net.datafaker.providers.base.Team',
    'net.datafaker.providers.base.University',
    'net.datafaker.providers.entertainment.Babylon5',
    'net.datafaker.providers.entertainment.BackToTheFuture',
    'net.datafaker.providers.entertainment.BreakingBad',
    'net.datafaker.providers.entertainment.FreshPrinceOfBelAir',
    'net.datafaker.providers.entertainment.FullmetalAlchemist',
    'net.datafaker.providers.entertainment.HeyArnold',
    'net.datafaker.providers.entertainment.Hobbit',
    'net.datafaker.providers.entertainment.HowToTrainYourDragon',
    'net.datafaker.providers.entertainment.OscarMovie',
    'net.datafaker.providers.entertainment.RuPaulDragRace',
    'net.datafaker.providers.entertainment.Supernatural',
    'net.datafaker.providers.entertainment.SwordArtOnline',
    'net.datafaker.providers.entertainment.TheExpanse',
    'net.datafaker.providers.entertainment.TheRoom',
    'net.datafaker.providers.food.FoodFaker',
    'net.datafaker.providers.food.Tea',
    'net.datafaker.providers.sport.Cricket',
    'net.datafaker.providers.sport.Formula1',
    'net.datafaker.providers.sport.Volleyball',
    'net.datafaker.providers.videogame.ClashOfClans',
    'net.datafaker.providers.videogame.Control',
    'net.datafaker.providers.videogame.DarkSouls',
    'net.datafaker.providers.videogame.ElderScrolls',
    'net.datafaker.providers.videogame.Esports',
    'net.datafaker.providers.videogame.SoulKnight',
    'net.datafaker.providers.videogame.SuperSmashBros',
    'net.datafaker.providers.videogame.Zelda',
    'net.datafaker.service.FakeValuesGrouping',
    'net.datafaker.transformations.CompositeField',
    'net.datafaker.transformations.Schema',
    'net.datafaker.transformations.sql.SqlTransformer'
]

# 计算类的数量
count = class_names.count('') // 2

print(f"类的数量是: {count}")