class_entries =[
    'java.software.amazon.event.ruler.Patterns\t0',
    'java.software.amazon.event.ruler.CompositeByteTransition\t0',
    'java.software.amazon.event.ruler.ByteState\t0',
    'java.software.amazon.event.ruler.Range\t0',
    'software.amazon.event.ruler.input.InputByte\t1',
    'software.amazon.event.ruler.input.InputWildcard\t1',
    'java.software.amazon.event.ruler.input.ParseException\t1',
    'java.software.amazon.event.ruler.ByteMatch\t0',
    'java.software.amazon.event.ruler.IntIntMap\t0',
    'org.jfree.chart.annotations.XYNoteAnnotation\t1',
    'org.jfree.data.xy.WindDataItem\t1',
    'org.jfree.chart.axis.SubCategoryAxis\t1',
    'org.jfree.data.general.WaferMapDataset\t1',
    'org.jfree.chart.axis.NumberTickUnitSource\t1',
    'org.jfree.chart.encoders.ImageEncoderFactory\t1',
    'org.jfree.data.resources.DataPackageResources_ru\t1',
    'org.jfree.chart.ui.StrokeSample\t1',
    'org.jfree.chart.axis.NumberTickUnit\t1',
    'org.jfree.chart.title.TextTitle\t1',
    'org.jfree.data.category.DefaultCategoryDataset\t1',
    'org.jfree.chart.axis.CategoryTick\t1',
    'org.jfree.chart.labels.StandardXYToolTipGenerator\t1',
    'org.jfree.data.statistics.HistogramDataset\t1',
    'org.jfree.chart.renderer.category.StatisticalLineAndShapeRenderer\t0',
    'org.jfree.chart.event.ChartProgressEvent\t1',
    'org.jfree.chart.editor.DefaultNumberAxisEditor\t1',
    'org.jfree.data.time.DateRange\t1',
    'org.jfree.chart.renderer.WaferMapRenderer\t1',
    'org.jfree.chart.util.AttrStringUtils\t1',
    'org.jfree.chart.entity.LegendItemEntity\t1',
    'org.jfree.data.general.DefaultHeatMapDataset\t1',
    'org.jfree.data.flow.DefaultFlowDataset\t1',
    'org.jfree.chart.plot.IntervalMarker\t1',
    'org.jfree.chart.renderer.RendererUtils\t1',
    'org.jfree.data.xml.KeyHandler\t1',
    'org.jfree.chart.editor.ChartEditorManager\t1',
    'org.jfree.chart.annotations.CategoryLineAnnotation\t1',
    'org.jfree.chart.axis.PeriodAxisLabelInfo\t1',
    'org.jfree.data.flow.FlowKey\t1',
    'org.jfree.chart.text.TextBlock\t1',
    'org.jfree.data.general.AbstractSeriesDataset\t0',
    'org.jfree.data.general.HeatMapUtils\t0',
    'org.jfree.data.xy.YIntervalDataItem\t1',
    'org.jfree.chart.title.LegendTitle\t1',
    'org.jfree.data.xy.MatrixSeriesCollection\t1',
    'org.jfree.chart.text.TextBox\t1',
    'org.jfree.chart.renderer.category.GradientBarPainter\t1',
    'org.jfree.chart.util.UnitType\t0',
    'org.jfree.chart.entity.JFreeChartEntity\t1',
    'org.jfree.chart.labels.IntervalCategoryToolTipGenerator\t1',
    'org.jfree.chart.labels.BubbleXYItemLabelGenerator\t1',
    'org.jfree.chart.renderer.AreaRendererEndType\t1',
    'org.jfree.chart.text.G2TextMeasurer\t1',
    'org.jfree.data.jdbc.JDBCPieDataset\t1',
    'org.jfree.chart.plot.dial.StandardDialRange\t1',
    'org.jfree.chart.annotations.XYLineAnnotation\t0',
    'org.jfree.chart.plot.dial.StandardDialScale\t1',
    'org.jfree.chart.util.HMSNumberFormat\t1',
    'org.jfree.chart.entity.StandardEntityCollection\t1',
    'org.jfree.data.xy.DefaultOHLCDataset\t1',
    'org.jfree.chart.util.PaintList\t1',
    'org.jfree.data.KeyToGroupMap\t1',
    'org.jfree.chart.plot.PieLabelLinkStyle\t1',
    'org.jfree.data.statistics.MeanAndStandardDeviation\t1',
    'org.jfree.chart.plot.CombinedDomainXYPlot\t1',
    'org.jfree.data.xy.XYSeries\t1',
    'org.jfree.data.general.AbstractDataset\t0',
    'org.jfree.chart.annotations.XYTitleAnnotation\t1',
    'org.jfree.chart.axis.PeriodAxis\t1',
    'org.jfree.chart.labels.CustomXYToolTipGenerator\t1',
    'org.jfree.chart.axis.TickUnits\t1',
    'org.jfree.chart.util.XYCoordinateType\t1',
    'org.jfree.data.category.SlidingCategoryDataset\t1',
    'org.jfree.chart.title.LegendGraphic\t1',
    'org.jfree.data.KeyedValueComparator\t1',
    'org.jfree.chart.util.PaintAlpha\t1',
    'org.jfree.data.time.TimeSeriesDataItem\t1',
    'org.jfree.chart.renderer.category.LineAndShapeRenderer\t1',
    'org.jfree.data.general.DatasetGroup\t1',
    'org.jfree.chart.renderer.category.CategoryStepRenderer\t0',
    'org.jfree.chart.labels.StandardXYSeriesLabelGenerator\t1',
    'org.jfree.data.KeyedObjects2D\t1',
    'org.jfree.chart.axis.LogarithmicAxis\t0',
    'org.jfree.chart.PaintMap\t1',
    'org.jfree.chart.labels.SymbolicXYItemLabelGenerator\t1',
    'org.jfree.chart.event.RendererChangeEvent\t1',
    'org.jfree.data.category.DefaultIntervalCategoryDataset\t1',
    'org.jfree.chart.labels.ItemLabelPosition\t1',
    'org.jfree.chart.plot.CenterTextMode\t0',
    'org.jfree.data.statistics.Regression\t0',
    'org.jfree.chart.axis.DateTickUnit\t1',
    'org.jfree.chart.event.AnnotationChangeEvent\t1',
    'org.jfree.chart.util.RelativeDateFormat\t1',
    'org.jfree.data.gantt.TaskSeriesCollection\t1',
    'org.jfree.data.xy.DefaultXYZDataset\t1',
    'org.jfree.data.DefaultKeyedValues\t1',
    'org.jfree.data.time.RegularTimePeriod\t0',
    'org.jfree.data.xy.XYSeriesCollection\t1',
    'org.jfree.chart.renderer.xy.StackedXYBarRenderer\t1',
    'org.jfree.chart.urls.CustomCategoryURLGenerator\t1',
    'org.jfree.chart.renderer.xy.VectorRenderer\t1',
    'org.jfree.chart.axis.SymbolAxis\t1',
    'org.jfree.chart.renderer.xy.StandardXYBarPainter\t1',
    'org.jfree.chart.axis.StandardTickUnitSource\t1',
    'org.jfree.chart.labels.ItemLabelAnchor\t1',
    'org.jfree.data.statistics.HistogramBin\t1',
    'org.jfree.chart.renderer.xy.XYStepRenderer\t1',
    'org.jfree.chart.ChartFactory\t0',
    'org.jfree.chart.plot.CategoryMarker\t1',
    'org.jfree.chart.entity.PieSectionEntity\t1',
    'org.jfree.chart.block.LengthConstraintType\t1',
    'org.jfree.data.general.DatasetChangeEvent\t1',
    'org.jfree.chart.renderer.xy.XYDotRenderer\t1',
    'org.jfree.chart.labels.StandardCategorySeriesLabelGenerator\t1',
    'org.jfree.chart.renderer.xy.StackedXYAreaRenderer\t0',
    'org.jfree.chart.renderer.xy.StandardXYItemRenderer\t1',
    'org.jfree.chart.util.DirectionalGradientPaintTransformer\t1'
]
# jfree
# [
#     'org.jfree.chart.annotations.XYNoteAnnotation\t1',
#     'org.jfree.data.xy.WindDataItem\t1',
#     'org.jfree.chart.axis.SubCategoryAxis\t1',
#     'org.jfree.data.general.WaferMapDataset\t1',
#     'org.jfree.chart.axis.NumberTickUnitSource\t1',
#     'org.jfree.chart.encoders.ImageEncoderFactory\t1',
#     'org.jfree.data.resources.DataPackageResources_ru\t1',
#     'org.jfree.chart.ui.StrokeSample\t1',
#     'org.jfree.chart.axis.NumberTickUnit\t1',
#     'org.jfree.chart.title.TextTitle\t1',
#     'org.jfree.data.category.DefaultCategoryDataset\t1',
#     'org.jfree.chart.axis.CategoryTick\t1',
#     'org.jfree.chart.labels.StandardXYToolTipGenerator\t1',
#     'org.jfree.data.statistics.HistogramDataset\t1',
#     'org.jfree.chart.renderer.category.StatisticalLineAndShapeRenderer\t1',
#     'org.jfree.chart.event.ChartProgressEvent\t1',
#     'org.jfree.chart.editor.DefaultNumberAxisEditor\t1',
#     'org.jfree.data.time.DateRange\t1',
#     'org.jfree.chart.renderer.WaferMapRenderer\t1',
#     'org.jfree.chart.util.AttrStringUtils\t1',
#     'org.jfree.chart.entity.LegendItemEntity\t1',
#     'org.jfree.data.general.DefaultHeatMapDataset\t1',
#     'org.jfree.data.flow.DefaultFlowDataset\t1',
#     'org.jfree.chart.plot.IntervalMarker\t1',
#     'org.jfree.chart.renderer.RendererUtils\t1',
#     'org.jfree.data.xml.KeyHandler\t1',
#     'org.jfree.chart.editor.ChartEditorManager\t1',
#     'org.jfree.chart.annotations.CategoryLineAnnotation\t1',
#     'org.jfree.chart.axis.PeriodAxisLabelInfo\t1',
#     'org.jfree.data.flow.FlowKey\t1',
#     'org.jfree.chart.text.TextBlock\t1',
#     'org.jfree.data.general.AbstractSeriesDataset\t0',
#     'org.jfree.data.general.HeatMapUtils\t0',
#     'org.jfree.data.xy.YIntervalDataItem\t1',
#     'org.jfree.chart.title.LegendTitle\t1',
#     'org.jfree.data.xy.MatrixSeriesCollection\t1',
#     'org.jfree.chart.text.TextBox\t1',
#     'org.jfree.chart.renderer.category.GradientBarPainter\t1',
#     'org.jfree.chart.util.UnitType\t0',
#     'org.jfree.chart.entity.JFreeChartEntity\t0',
#     'org.jfree.chart.labels.IntervalCategoryToolTipGenerator\t1',
#     'org.jfree.chart.labels.BubbleXYItemLabelGenerator\t1',
#     'org.jfree.chart.renderer.AreaRendererEndType\t1',
#     'org.jfree.chart.text.G2TextMeasurer\t1',
#     'org.jfree.data.jdbc.JDBCPieDataset\t1',
#     'org.jfree.chart.plot.dial.StandardDialRange\t1',
#     'org.jfree.chart.annotations.XYLineAnnotation\t1',
#     'org.jfree.chart.plot.dial.StandardDialScale\t1',
#     'org.jfree.chart.util.HMSNumberFormat\t1',
#     'org.jfree.chart.entity.StandardEntityCollection\t1',
#     'org.jfree.data.xy.DefaultOHLCDataset\t1',
#     'org.jfree.chart.util.PaintList\t1',
#     'org.jfree.data.KeyToGroupMap\t1',
#     'org.jfree.chart.plot.PieLabelLinkStyle\t1',
#     'org.jfree.data.statistics.MeanAndStandardDeviation\t1',
#     'org.jfree.chart.plot.CombinedDomainXYPlot\t1',
#     'org.jfree.data.xy.XYSeries\t1',
#     'org.jfree.data.general.AbstractDataset\t0',
#     'org.jfree.chart.annotations.XYTitleAnnotation\t1',
#     'org.jfree.chart.axis.PeriodAxis\t1',
#     'org.jfree.chart.labels.CustomXYToolTipGenerator\t1',
#     'org.jfree.chart.axis.TickUnits\t1',
#     'org.jfree.chart.util.XYCoordinateType\t1',
#     'org.jfree.data.category.SlidingCategoryDataset\t1',
#     'org.jfree.chart.title.LegendGraphic\t1',
#     'org.jfree.data.KeyedValueComparator\t1',
#     'org.jfree.chart.util.PaintAlpha\t1',
#     'org.jfree.data.time.TimeSeriesDataItem\t0',
#     'org.jfree.chart.renderer.category.LineAndShapeRenderer\t1',
#     'org.jfree.data.general.DatasetGroup\t1',
#     'org.jfree.chart.renderer.category.CategoryStepRenderer\t0',
#     'org.jfree.chart.labels.StandardXYSeriesLabelGenerator\t1',
#     'org.jfree.data.KeyedObjects2D\t1',
#     'org.jfree.chart.axis.LogarithmicAxis\t0',
#     'org.jfree.chart.PaintMap\t1',
#     'org.jfree.chart.labels.SymbolicXYItemLabelGenerator\t1',
#     'org.jfree.chart.event.RendererChangeEvent\t1',
#     'org.jfree.data.category.DefaultIntervalCategoryDataset\t1',
#     'org.jfree.chart.labels.ItemLabelPosition\t1',
#     'org.jfree.chart.plot.CenterTextMode\t0',
#     'org.jfree.data.statistics.Regression\t0',
#     'org.jfree.chart.axis.DateTickUnit\t1',
#     'org.jfree.chart.event.AnnotationChangeEvent\t1',
#     'org.jfree.chart.util.RelativeDateFormat\t1',
#     'org.jfree.data.gantt.TaskSeriesCollection\t1',
#     'org.jfree.data.xy.DefaultXYZDataset\t1',
#     'org.jfree.data.DefaultKeyedValues\t1',
#     'org.jfree.data.time.RegularTimePeriod\t0',
#     'org.jfree.data.xy.XYSeriesCollection\t1',
#     'org.jfree.chart.renderer.xy.StackedXYBarRenderer\t1',
#     'org.jfree.chart.urls.CustomCategoryURLGenerator\t1',
#     'org.jfree.chart.renderer.xy.VectorRenderer\t1',
#     'org.jfree.chart.axis.SymbolAxis\t1',
#     'org.jfree.chart.renderer.xy.StandardXYBarPainter\t1',
#     'org.jfree.chart.axis.StandardTickUnitSource\t1',
#     'org.jfree.chart.labels.ItemLabelAnchor\t1',
#     'org.jfree.data.statistics.HistogramBin\t1',
#     'org.jfree.chart.renderer.xy.XYStepRenderer\t0',
#     'org.jfree.chart.ChartFactory\t0',
#     'org.jfree.chart.plot.CategoryMarker\t1',
#     'org.jfree.chart.entity.PieSectionEntity\t1',
#     'org.jfree.chart.block.LengthConstraintType\t1',
#     'org.jfree.data.general.DatasetChangeEvent\t1',
#     'org.jfree.chart.renderer.xy.XYDotRenderer\t1',
#     'org.jfree.chart.labels.StandardCategorySeriesLabelGenerator\t1',
#     'org.jfree.chart.renderer.xy.StackedXYAreaRenderer\t0',
#     'org.jfree.chart.renderer.xy.StandardXYItemRenderer\t1',
#     'org.jfree.chart.util.DirectionalGradientPaintTransformer\t1'
# ]
# 处理每个条目，提取类名和计数，生成目标格式
result = {}
for entry in class_entries:
    class_path, count_str = entry.split('\t')
    class_name = class_path.split('.')[-1]
    count = int(count_str)
    # 根据计数设置对应的值
    result[class_name] = (1, 0) if count == 0 else (2, count)

# 按照要求的格式输出
output = "{\n"
for name, pair in result.items():
    output += f'    "{name}": {pair},\n'
output += "}"

print(output)