
class_names = [
    'com.google.gson.JsonObject',
    'com.google.gson.JsonPrimitive',
    'com.google.gson.internal.Primitives',
    'com.google.gson.internal.PreJava9DateFormatProvider',
    'com.google.gson.internal.Streams',
    'com.google.gson.internal.NonNullElementWrapperList',
    'com.google.gson.internal.bind.NumberTypeAdapter',
    'com.google.gson.internal.bind.CollectionTypeAdapterFactory',
    'com.google.gson.internal.Excluder',
    'com.google.gson.internal.reflect.ReflectionHelper',
    'com.google.gson.internal.bind.TreeTypeAdapter'
]


#lang
# [
#     'org.apache.commons.lang3.LocaleUtils',
#     'org.apache.commons.lang3.text.translate.CharSequenceTranslator',
#     'org.apache.commons.lang3.time.FastDateParser',
#     'org.apache.commons.lang3.builder.CompareToBuilder',
#     'org.apache.commons.lang3.mutable.MutableInt',
#     'org.apache.commons.lang3.time.FastDateFormat',
#     'org.apache.commons.lang3.concurrent.ConcurrentRuntimeException',
#     'org.apache.commons.lang3.mutable.MutableByte',
#     'org.apache.commons.lang3.Conversion',
#     'org.apache.commons.lang3.mutable.MutableLong',
#     'org.apache.commons.lang3.time.DateUtils',
#     'org.apache.commons.lang3.builder.StandardToStringStyle',
#     'org.apache.commons.lang3.concurrent.BasicThreadFactory',
#     'org.apache.commons.lang3.builder.ToStringStyle',
#     'org.apache.commons.lang3.SerializationException',
#     'org.apache.commons.lang3.concurrent.ConcurrentException',
#     'org.apache.commons.lang3.text.translate.EntityArrays',
#     'org.apache.commons.lang3.time.DateFormatUtils',
#     'org.apache.commons.lang3.builder.EqualsBuilder',
#     'org.apache.commons.lang3.math.IEEE754rUtils'
# ]

# jfree
# [
#     'org.jfree.chart.annotations.XYNoteAnnotation',
#     'org.jfree.data.xy.WindDataItem',
#     'org.jfree.chart.axis.SubCategoryAxis',
#     'org.jfree.data.general.WaferMapDataset',
#     'org.jfree.chart.axis.NumberTickUnitSource',
#     'org.jfree.chart.encoders.ImageEncoderFactory',
#     'org.jfree.data.resources.DataPackageResources_ru',
#     'org.jfree.chart.ui.StrokeSample',
#     'org.jfree.chart.axis.NumberTickUnit',
#     'org.jfree.chart.title.TextTitle',
#     'org.jfree.data.category.DefaultCategoryDataset',
#     'org.jfree.chart.axis.CategoryTick',
#     'org.jfree.chart.labels.StandardXYToolTipGenerator',
#     'org.jfree.data.statistics.HistogramDataset',
#     'org.jfree.chart.renderer.category.StatisticalLineAndShapeRenderer',
#     'org.jfree.chart.event.ChartProgressEvent',
#     'org.jfree.chart.editor.DefaultNumberAxisEditor',
#     'org.jfree.data.time.DateRange',
#     'org.jfree.chart.renderer.WaferMapRenderer',
#     'org.jfree.chart.util.AttrStringUtils',
#     'org.jfree.chart.entity.LegendItemEntity',
#     'org.jfree.data.general.DefaultHeatMapDataset',
#     'org.jfree.data.flow.DefaultFlowDataset',
#     'org.jfree.chart.plot.IntervalMarker',
#     'org.jfree.chart.renderer.RendererUtils',
#     'org.jfree.data.xml.KeyHandler',
#     'org.jfree.chart.editor.ChartEditorManager',
#     'org.jfree.chart.annotations.CategoryLineAnnotation',
#     'org.jfree.chart.axis.PeriodAxisLabelInfo',
#     'org.jfree.data.flow.FlowKey',
#     'org.jfree.chart.text.TextBlock',
#     'org.jfree.data.general.AbstractSeriesDataset',
#     'org.jfree.data.general.HeatMapUtils',
#     'org.jfree.data.xy.YIntervalDataItem',
#     'org.jfree.chart.title.LegendTitle',
#     'org.jfree.data.xy.MatrixSeriesCollection',
#     'org.jfree.chart.text.TextBox',
#     'org.jfree.chart.renderer.category.GradientBarPainter',
#     'org.jfree.chart.util.UnitType',
#     'org.jfree.chart.entity.JFreeChartEntity',
#     'org.jfree.chart.labels.IntervalCategoryToolTipGenerator',
#     'org.jfree.chart.labels.BubbleXYItemLabelGenerator',
#     'org.jfree.chart.renderer.AreaRendererEndType',
#     'org.jfree.chart.text.G2TextMeasurer',
#     'org.jfree.data.jdbc.JDBCPieDataset',
#     'org.jfree.chart.plot.dial.StandardDialRange',
#     'org.jfree.chart.annotations.XYLineAnnotation',
#     'org.jfree.chart.plot.dial.StandardDialScale',
#     'org.jfree.chart.util.HMSNumberFormat',
#     'org.jfree.chart.entity.StandardEntityCollection',
#     'org.jfree.data.xy.DefaultOHLCDataset',
#     'org.jfree.chart.util.PaintList',
#     'org.jfree.data.KeyToGroupMap',
#     'org.jfree.chart.plot.PieLabelLinkStyle',
#     'org.jfree.data.statistics.MeanAndStandardDeviation',
#     'org.jfree.chart.plot.CombinedDomainXYPlot',
#     'org.jfree.data.xy.XYSeries',
#     'org.jfree.data.general.AbstractDataset',
#     'org.jfree.chart.annotations.XYTitleAnnotation',
#     'org.jfree.chart.axis.PeriodAxis',
#     'org.jfree.chart.labels.CustomXYToolTipGenerator',
#     'org.jfree.chart.axis.TickUnits',
#     'org.jfree.chart.util.XYCoordinateType',
#     'org.jfree.data.category.SlidingCategoryDataset',
#     'org.jfree.chart.title.LegendGraphic',
#     'org.jfree.data.KeyedValueComparator',
#     'org.jfree.chart.util.PaintAlpha',
#     'org.jfree.data.time.TimeSeriesDataItem',
#     'org.jfree.chart.renderer.category.LineAndShapeRenderer',
#     'org.jfree.data.general.DatasetGroup',
#     'org.jfree.chart.renderer.category.CategoryStepRenderer',
#     'org.jfree.chart.labels.StandardXYSeriesLabelGenerator',
#     'org.jfree.data.KeyedObjects2D',
#     'org.jfree.chart.axis.LogarithmicAxis',
#     'org.jfree.chart.PaintMap',
#     'org.jfree.chart.labels.SymbolicXYItemLabelGenerator',
#     'org.jfree.chart.event.RendererChangeEvent',
#     'org.jfree.data.category.DefaultIntervalCategoryDataset',
#     'org.jfree.chart.labels.ItemLabelPosition',
#     'org.jfree.chart.plot.CenterTextMode',
#     'org.jfree.data.statistics.Regression',
#     'org.jfree.chart.axis.DateTickUnit',
#     'org.jfree.chart.event.AnnotationChangeEvent',
#     'org.jfree.chart.util.RelativeDateFormat',
#     'org.jfree.data.gantt.TaskSeriesCollection',
#     'org.jfree.data.xy.DefaultXYZDataset',
#     'org.jfree.data.DefaultKeyedValues',
#     'org.jfree.data.time.RegularTimePeriod',
#     'org.jfree.data.xy.XYSeriesCollection',
#     'org.jfree.chart.renderer.xy.StackedXYBarRenderer',
#     'org.jfree.chart.urls.CustomCategoryURLGenerator',
#     'org.jfree.chart.renderer.xy.VectorRenderer',
#     'org.jfree.chart.axis.SymbolAxis',
#     'org.jfree.chart.renderer.xy.StandardXYBarPainter',
#     'org.jfree.chart.axis.StandardTickUnitSource',
#     'org.jfree.chart.labels.ItemLabelAnchor',
#     'org.jfree.data.statistics.HistogramBin',
#     'org.jfree.chart.renderer.xy.XYStepRenderer',
#     'org.jfree.chart.ChartFactory',
#     'org.jfree.chart.plot.CategoryMarker',
#     'org.jfree.chart.entity.PieSectionEntity',
#     'org.jfree.chart.block.LengthConstraintType',
#     'org.jfree.data.general.DatasetChangeEvent',
#     'org.jfree.chart.renderer.xy.XYDotRenderer',
#     'org.jfree.chart.labels.StandardCategorySeriesLabelGenerator',
#     'org.jfree.chart.renderer.xy.StackedXYAreaRenderer',
#     'org.jfree.chart.renderer.xy.StandardXYItemRenderer',
#     'org.jfree.chart.util.DirectionalGradientPaintTransformer'
# ]
# 提取类名部分
extracted_names = [class_name.split('.')[-1] for class_name in class_names]

# 打印原始格式的类名列表
print(extracted_names)

# 打印类的总数（去重后）
unique_classes = set(extracted_names)
print(f"总共有 {len(unique_classes)} 个不同的类")